# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

# jobs:
# - job: Build_Image
#   steps:
#   - task: Maven@3
#     inputs:
#       mavenPomFile: 'pom.xml'
#       mavenOptions: '-Xmx3072m'
#       javaHomeOption: 'JDKVersion'
#       jdkVersionOption: '1.8'
#       jdkArchitectureOption: 'x64'
#       publishJUnitResults: true
#       testResultsFiles: '**/surefire-reports/TEST-*.xml'
#       goals: 'package'
# - job: Push_Image
#   dependsOn: Build_Image
#   steps:
#   - bash: docker login -u vineelpellella -p ${DOCKER_ACCESS_TOKEN}
#   - bash: docker image tag memes-app:0.0.3-SNAPSHOT vineelpellella/memes-app
#   - bash: docker push vineelpellella/memes-app


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- bash: docker login -u vineelpellella -p $(DOCKER_ACCESS_TOKEN)
- bash: docker image tag memes-app:0.0.3-SNAPSHOT vineelpellella/memes-app
- bash: docker push vineelpellella/memes-app
