version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management    
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - memes
      
  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - 9411:9411
    networks:
      - memes
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always #Restart if there is a problem starting up
      
  memes-app:
    image: vineelpellella/memes-app
    mem_limit: 700m
    ports:
      - 8080:8080
    networks:
      - memes
    depends_on:
      - zipkin-server
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

networks:
  memes: